<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="hyjiacan.pinyin4net" Version="4.1.1" />
    <PackageReference Include="nacos-sdk-csharp" Version="1.3.10" />
    <PackageReference Include="Polly" Version="8.5.0" />
    <PackageReference Include="Serilog" Version="4.1.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="TinyPinyin" Version="1.1.0" />
    <PackageReference Include="Volo.Abp.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Volo.Abp.Autofac" Version="9.0.0" />
    <PackageReference Include="Volo.Abp.EventBus" Version="9.0.0" />
    <PackageReference Include="Volo.Abp.EventBus.Kafka" Version="9.0.0" />
  </ItemGroup>

</Project>
