//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XStudio.App.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XStudio.App.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加项 的本地化字符串。
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动画路径 的本地化字符串。
        /// </summary>
        internal static string AnimationPath {
            get {
                return ResourceManager.GetString("AnimationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘图标已打开，将隐藏窗口而不是关闭程序 的本地化字符串。
        /// </summary>
        internal static string AppClosingTip {
            get {
                return ResourceManager.GetString("AppClosingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询问 的本地化字符串。
        /// </summary>
        internal static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动补全文本框 的本地化字符串。
        /// </summary>
        internal static string AutoCompleteTextBox {
            get {
                return ResourceManager.GetString("AutoCompleteTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记 的本地化字符串。
        /// </summary>
        internal static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写基本信息 的本地化字符串。
        /// </summary>
        internal static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础布局 的本地化字符串。
        /// </summary>
        internal static string BasicLayout {
            get {
                return ResourceManager.GetString("BasicLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闪烁 的本地化字符串。
        /// </summary>
        internal static string Blink {
            get {
                return ResourceManager.GetString("Blink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 博客 的本地化字符串。
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框 的本地化字符串。
        /// </summary>
        internal static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画刷 的本地化字符串。
        /// </summary>
        internal static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮 的本地化字符串。
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义按钮 的本地化字符串。
        /// </summary>
        internal static string ButtonCustom {
            get {
                return ResourceManager.GetString("ButtonCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮组 的本地化字符串。
        /// </summary>
        internal static string ButtonGroup {
            get {
                return ResourceManager.GetString("ButtonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日历 的本地化字符串。
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带时钟的日历 的本地化字符串。
        /// </summary>
        internal static string CalendarWithClock {
            get {
                return ResourceManager.GetString("CalendarWithClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片 的本地化字符串。
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮播 的本地化字符串。
        /// </summary>
        internal static string Carousel {
            get {
                return ResourceManager.GetString("Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否重启以更改语言？ 的本地化字符串。
        /// </summary>
        internal static string ChangeLangAsk {
            get {
                return ResourceManager.GetString("ChangeLangAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对话气泡 的本地化字符串。
        /// </summary>
        internal static string ChatBubble {
            get {
                return ResourceManager.GetString("ChatBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讨论室 的本地化字符串。
        /// </summary>
        internal static string Chatroom {
            get {
                return ResourceManager.GetString("Chatroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复选框 的本地化字符串。
        /// </summary>
        internal static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多选组合框 的本地化字符串。
        /// </summary>
        internal static string CheckComboBox {
            get {
                return ResourceManager.GetString("CheckComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆形布局 的本地化字符串。
        /// </summary>
        internal static string CirclePanel {
            get {
                return ResourceManager.GetString("CirclePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击计数 的本地化字符串。
        /// </summary>
        internal static string Click2Count {
            get {
                return ResourceManager.GetString("Click2Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时钟 的本地化字符串。
        /// </summary>
        internal static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭主窗口对话框 的本地化字符串。
        /// </summary>
        internal static string CloseMainWindowDialog {
            get {
                return ResourceManager.GetString("CloseMainWindowDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色拾取器 的本地化字符串。
        /// </summary>
        internal static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分栏偏移 的本地化字符串。
        /// </summary>
        internal static string ColumnOffset {
            get {
                return ResourceManager.GetString("ColumnOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分栏间隔 的本地化字符串。
        /// </summary>
        internal static string ColumnSpacing {
            get {
                return ResourceManager.GetString("ColumnSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合框 的本地化字符串。
        /// </summary>
        internal static string ComboBox {
            get {
                return ResourceManager.GetString("ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敬请期待 的本地化字符串。
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论 的本地化字符串。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般 的本地化字符串。
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对比滑块 的本地化字符串。
        /// </summary>
        internal static string CompareSlider {
            get {
                return ResourceManager.GetString("CompareSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是内容 的本地化字符串。
        /// </summary>
        internal static string ContentDemoStr {
            get {
                return ResourceManager.GetString("ContentDemoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贡献者 的本地化字符串。
        /// </summary>
        internal static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件 的本地化字符串。
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面流 的本地化字符串。
        /// </summary>
        internal static string CoverFlow {
            get {
                return ResourceManager.GetString("CoverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面视图 的本地化字符串。
        /// </summary>
        internal static string CoverView {
            get {
                return ResourceManager.GetString("CoverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险 的本地化字符串。
        /// </summary>
        internal static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据展示 的本地化字符串。
        /// </summary>
        internal static string DataDisplay {
            get {
                return ResourceManager.GetString("DataDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据录入 的本地化字符串。
        /// </summary>
        internal static string DataEntry {
            get {
                return ResourceManager.GetString("DataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据表格 的本地化字符串。
        /// </summary>
        internal static string DataGrid {
            get {
                return ResourceManager.GetString("DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期选择器 的本地化字符串。
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期时间选择器 的本地化字符串。
        /// </summary>
        internal static string DateTimePicker {
            get {
                return ResourceManager.GetString("DateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示例 的本地化字符串。
        /// </summary>
        internal static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对话框 的本地化字符串。
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对话框示例 的本地化字符串。
        /// </summary>
        internal static string DialogDemo {
            get {
                return ResourceManager.GetString("DialogDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分割线 的本地化字符串。
        /// </summary>
        internal static string Divider {
            get {
                return ResourceManager.GetString("Divider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文文档 的本地化字符串。
        /// </summary>
        internal static string Doc_cn {
            get {
                return ResourceManager.GetString("Doc_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文文档 的本地化字符串。
        /// </summary>
        internal static string Doc_en {
            get {
                return ResourceManager.GetString("Doc_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文献资料 的本地化字符串。
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这里拖拽 的本地化字符串。
        /// </summary>
        internal static string DragHere {
            get {
                return ResourceManager.GetString("DragHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽屉 的本地化字符串。
        /// </summary>
        internal static string Drawer {
            get {
                return ResourceManager.GetString("Drawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果 的本地化字符串。
        /// </summary>
        internal static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元素组 的本地化字符串。
        /// </summary>
        internal static string ElementGroup {
            get {
                return ResourceManager.GetString("ElementGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空状态 的本地化字符串。
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开框 的本地化字符串。
        /// </summary>
        internal static string Expander {
            get {
                return ResourceManager.GetString("Expander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 严重 的本地化字符串。
        /// </summary>
        internal static string Fatal {
            get {
                return ResourceManager.GetString("Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈 的本地化字符串。
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹性盒子 的本地化字符串。
        /// </summary>
        internal static string FlexPanel {
            get {
                return ResourceManager.GetString("FlexPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻页时钟 的本地化字符串。
        /// </summary>
        internal static string FlipClock {
            get {
                return ResourceManager.GetString("FlipClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漂浮块 的本地化字符串。
        /// </summary>
        internal static string FloatingBlock {
            get {
                return ResourceManager.GetString("FloatingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流文档 的本地化字符串。
        /// </summary>
        internal static string FlowDocument {
            get {
                return ResourceManager.GetString("FlowDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流文档单页视图 的本地化字符串。
        /// </summary>
        internal static string FlowDocumentPageViewer {
            get {
                return ResourceManager.GetString("FlowDocumentPageViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流文档查看器 的本地化字符串。
        /// </summary>
        internal static string FlowDocumentReader {
            get {
                return ResourceManager.GetString("FlowDocumentReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流文档滚动视图 的本地化字符串。
        /// </summary>
        internal static string FlowDocumentScrollViewer {
            get {
                return ResourceManager.GetString("FlowDocumentScrollViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航框架 的本地化字符串。
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 几何形状 的本地化字符串。
        /// </summary>
        internal static string Geometry {
            get {
                return ResourceManager.GetString("Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gif图片 的本地化字符串。
        /// </summary>
        internal static string GifImage {
            get {
                return ResourceManager.GetString("GifImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回到顶部 的本地化字符串。
        /// </summary>
        internal static string GotoTop {
            get {
                return ResourceManager.GetString("GotoTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像 的本地化字符串。
        /// </summary>
        internal static string Gravatar {
            get {
                return ResourceManager.GetString("Gravatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栅格 的本地化字符串。
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组框 的本地化字符串。
        /// </summary>
        internal static string GroupBox {
            get {
                return ResourceManager.GetString("GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组数 的本地化字符串。
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息通知 的本地化字符串。
        /// </summary>
        internal static string Growl {
            get {
                return ResourceManager.GetString("Growl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到有新版本！是否更新？ 的本地化字符串。
        /// </summary>
        internal static string GrowlAsk {
            get {
                return ResourceManager.GetString("GrowlAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息通知示例 的本地化字符串。
        /// </summary>
        internal static string GrowlDemo {
            get {
                return ResourceManager.GetString("GrowlDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败，请检查网络！ 的本地化字符串。
        /// </summary>
        internal static string GrowlError {
            get {
                return ResourceManager.GetString("GrowlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已崩溃~~~ 的本地化字符串。
        /// </summary>
        internal static string GrowlFatal {
            get {
                return ResourceManager.GetString("GrowlFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天的天气不错~~~ 的本地化字符串。
        /// </summary>
        internal static string GrowlInfo {
            get {
                return ResourceManager.GetString("GrowlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件保存成功！ 的本地化字符串。
        /// </summary>
        internal static string GrowlSuccess {
            get {
                return ResourceManager.GetString("GrowlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘空间快要满了！ 的本地化字符串。
        /// </summary>
        internal static string GrowlWarning {
            get {
                return ResourceManager.GetString("GrowlWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阴影画笔生成器 的本地化字符串。
        /// </summary>
        internal static string HatchBrushGenerator {
            get {
                return ResourceManager.GetString("HatchBrushGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蜂窝布局 的本地化字符串。
        /// </summary>
        internal static string HoneycombPanel {
            get {
                return ResourceManager.GetString("HoneycombPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 混合布局 的本地化字符串。
        /// </summary>
        internal static string HybridLayout {
            get {
                return ResourceManager.GetString("HybridLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 的本地化字符串。
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片块 的本地化字符串。
        /// </summary>
        internal static string ImageBlock {
            get {
                return ResourceManager.GetString("ImageBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片浏览器 的本地化字符串。
        /// </summary>
        internal static string ImageBrowser {
            get {
                return ResourceManager.GetString("ImageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片选择器 的本地化字符串。
        /// </summary>
        internal static string ImageSelector {
            get {
                return ResourceManager.GetString("ImageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索引 的本地化字符串。
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交互 的本地化字符串。
        /// </summary>
        internal static string Interacting {
            get {
                return ResourceManager.GetString("Interacting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可交互对话框 的本地化字符串。
        /// </summary>
        internal static string InteractiveDialog {
            get {
                return ResourceManager.GetString("InteractiveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是手机号码 的本地化字符串。
        /// </summary>
        internal static string IsNotPhone {
            get {
                return ResourceManager.GetString("IsNotPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找类似 {0} 的本地化字符串。 的本地化字符串。
        /// </summary>
        internal static string LangComment {
            get {
                return ResourceManager.GetString("LangComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表框 的本地化字符串。
        /// </summary>
        internal static string ListBox {
            get {
                return ResourceManager.GetString("ListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表视图 的本地化字符串。
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载条 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大镜 的本地化字符串。
        /// </summary>
        internal static string Magnifier {
            get {
                return ResourceManager.GetString("Magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息框 的本地化字符串。
        /// </summary>
        internal static string MessageBox {
            get {
                return ResourceManager.GetString("MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杂项 的本地化字符串。
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变形动画 的本地化字符串。
        /// </summary>
        internal static string Morphing_Animation {
            get {
                return ResourceManager.GetString("Morphing Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航 的本地化字符串。
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建窗口 的本地化字符串。
        /// </summary>
        internal static string NewWindow {
            get {
                return ResourceManager.GetString("NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面通知 的本地化字符串。
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘图标 的本地化字符串。
        /// </summary>
        internal static string NotifyIcon {
            get {
                return ResourceManager.GetString("NotifyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值选择控件 的本地化字符串。
        /// </summary>
        internal static string NumericUpDown {
            get {
                return ResourceManager.GetString("NumericUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开背景模糊窗口 的本地化字符串。
        /// </summary>
        internal static string OpenBlurWindow {
            get {
                return ResourceManager.GetString("OpenBlurWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开常规窗口 的本地化字符串。
        /// </summary>
        internal static string OpenCommonWindow {
            get {
                return ResourceManager.GetString("OpenCommonWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开自定义内容窗口 的本地化字符串。
        /// </summary>
        internal static string OpenCustomContentWindow {
            get {
                return ResourceManager.GetString("OpenCustomContentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开自定义消息窗口 的本地化字符串。
        /// </summary>
        internal static string OpenCustomMessageWindow {
            get {
                return ResourceManager.GetString("OpenCustomMessageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开自定义非客户端区域窗口 的本地化字符串。
        /// </summary>
        internal static string OpenCustomNonClientAreaWindow {
            get {
                return ResourceManager.GetString("OpenCustomNonClientAreaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开辉光窗口 的本地化字符串。
        /// </summary>
        internal static string OpenGlowWindow {
            get {
                return ResourceManager.GetString("OpenGlowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开图片浏览器 的本地化字符串。
        /// </summary>
        internal static string OpenImageBrowser {
            get {
                return ResourceManager.GetString("OpenImageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开消息窗口 的本地化字符串。
        /// </summary>
        internal static string OpenMessageWindow {
            get {
                return ResourceManager.GetString("OpenMessageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开鼠标跟随窗口 的本地化字符串。
        /// </summary>
        internal static string OpenMouseFollowWindow {
            get {
                return ResourceManager.GetString("OpenMouseFollowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开原生常规窗口 的本地化字符串。
        /// </summary>
        internal static string OpenNativeCommonWindow {
            get {
                return ResourceManager.GetString("OpenNativeCommonWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开导航窗口 的本地化字符串。
        /// </summary>
        internal static string OpenNavigationWindow {
            get {
                return ResourceManager.GetString("OpenNavigationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开无非客户端区域可拖拽窗口 的本地化字符串。
        /// </summary>
        internal static string OpenNoNonClientAreaDragableWindow {
            get {
                return ResourceManager.GetString("OpenNoNonClientAreaDragableWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开面板 的本地化字符串。
        /// </summary>
        internal static string OpenPanel {
            get {
                return ResourceManager.GetString("OpenPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开精灵 的本地化字符串。
        /// </summary>
        internal static string OpenSprite {
            get {
                return ResourceManager.GetString("OpenSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开触摸拖动窗口 的本地化字符串。
        /// </summary>
        internal static string OpenTouchDragMoveWindow {
            get {
                return ResourceManager.GetString("OpenTouchDragMoveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮廓文本 的本地化字符串。
        /// </summary>
        internal static string OutlineText {
            get {
                return ResourceManager.GetString("OutlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页码条 的本地化字符串。
        /// </summary>
        internal static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码框 的本地化字符串。
        /// </summary>
        internal static string PasswordBox {
            get {
                return ResourceManager.GetString("PasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIN码框 的本地化字符串。
        /// </summary>
        internal static string PinBox {
            get {
                return ResourceManager.GetString("PinBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入... 的本地化字符串。
        /// </summary>
        internal static string PleaseInput {
            get {
                return ResourceManager.GetString("PleaseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍后... 的本地化字符串。
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入内容 的本地化字符串。
        /// </summary>
        internal static string PlsEnterContent {
            get {
                return ResourceManager.GetString("PlsEnterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入邮箱 的本地化字符串。
        /// </summary>
        internal static string PlsEnterEmail {
            get {
                return ResourceManager.GetString("PlsEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入关键字 的本地化字符串。
        /// </summary>
        internal static string PlsEnterKey {
            get {
                return ResourceManager.GetString("PlsEnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气泡提示 的本地化字符串。
        /// </summary>
        internal static string Poptip {
            get {
                return ResourceManager.GetString("Poptip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上左;上边;上右;右上;右边;右下;下右;下边;下左;左下;左边;左上 的本地化字符串。
        /// </summary>
        internal static string PoptipPositionStr {
            get {
                return ResourceManager.GetString("PoptipPositionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实用例子 的本地化字符串。
        /// </summary>
        internal static string PracticalDemos {
            get {
                return ResourceManager.GetString("PracticalDemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        internal static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览滑块 的本地化字符串。
        /// </summary>
        internal static string PreviewSlider {
            get {
                return ResourceManager.GetString("PreviewSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主要 的本地化字符串。
        /// </summary>
        internal static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度条 的本地化字符串。
        /// </summary>
        internal static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度按钮 的本地化字符串。
        /// </summary>
        internal static string ProgressButton {
            get {
                return ResourceManager.GetString("ProgressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 的本地化字符串。
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性编辑器 的本地化字符串。
        /// </summary>
        internal static string PropertyGrid {
            get {
                return ResourceManager.GetString("PropertyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按住说话 的本地化字符串。
        /// </summary>
        internal static string PushToTalk {
            get {
                return ResourceManager.GetString("PushToTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ群 的本地化字符串。
        /// </summary>
        internal static string QQGroup {
            get {
                return ResourceManager.GetString("QQGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选按钮 的本地化字符串。
        /// </summary>
        internal static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围滑块 的本地化字符串。
        /// </summary>
        internal static string RangeSlider {
            get {
                return ResourceManager.GetString("RangeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评分 的本地化字符串。
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群友推荐 的本地化字符串。
        /// </summary>
        internal static string Recommendation {
            get {
                return ResourceManager.GetString("Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相对布局 的本地化字符串。
        /// </summary>
        internal static string RelativePanel {
            get {
                return ResourceManager.GetString("RelativePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除项 的本地化字符串。
        /// </summary>
        internal static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复按钮 的本地化字符串。
        /// </summary>
        internal static string RepeatButton {
            get {
                return ResourceManager.GetString("RepeatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复 的本地化字符串。
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码仓库 的本地化字符串。
        /// </summary>
        internal static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应式布局 的本地化字符串。
        /// </summary>
        internal static string ResponsiveLayout {
            get {
                return ResourceManager.GetString("ResponsiveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 富文本框 的本地化字符串。
        /// </summary>
        internal static string RichTextBox {
            get {
                return ResourceManager.GetString("RichTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这里右击 的本地化字符串。
        /// </summary>
        internal static string RightClickHere {
            get {
                return ResourceManager.GetString("RightClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚动块 的本地化字符串。
        /// </summary>
        internal static string RunningBlock {
            get {
                return ResourceManager.GetString("RunningBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图 的本地化字符串。
        /// </summary>
        internal static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚动视图 的本地化字符串。
        /// </summary>
        internal static string ScrollViewer {
            get {
                return ResourceManager.GetString("ScrollViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索栏 的本地化字符串。
        /// </summary>
        internal static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中 的本地化字符串。
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送通知 的本地化字符串。
        /// </summary>
        internal static string SendNotification {
            get {
                return ResourceManager.GetString("SendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 徽章 的本地化字符串。
        /// </summary>
        internal static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在当前窗口显示 的本地化字符串。
        /// </summary>
        internal static string ShowInCurrentWindow {
            get {
                return ResourceManager.GetString("ShowInCurrentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在主窗口显示 的本地化字符串。
        /// </summary>
        internal static string ShowInMainWindow {
            get {
                return ResourceManager.GetString("ShowInMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示行号 的本地化字符串。
        /// </summary>
        internal static string ShowRowNumber {
            get {
                return ResourceManager.GetString("ShowRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 侧边菜单 的本地化字符串。
        /// </summary>
        internal static string SideMenu {
            get {
                return ResourceManager.GetString("SideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滑块 的本地化字符串。
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分割按钮 的本地化字符串。
        /// </summary>
        internal static string SplitButton {
            get {
                return ResourceManager.GetString("SplitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精灵 的本地化字符串。
        /// </summary>
        internal static string Sprite {
            get {
                return ResourceManager.GetString("Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始截图 的本地化字符串。
        /// </summary>
        internal static string StartScreenshot {
            get {
                return ResourceManager.GetString("StartScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保持打开 的本地化字符串。
        /// </summary>
        internal static string StaysOpen {
            get {
                return ResourceManager.GetString("StaysOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 的本地化字符串。
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤条 的本地化字符串。
        /// </summary>
        internal static string StepBar {
            get {
                return ResourceManager.GetString("StepBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式模板 的本地化字符串。
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子标题 的本地化字符串。
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项卡控件 的本地化字符串。
        /// </summary>
        internal static string TabControl {
            get {
                return ResourceManager.GetString("TabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正文 的本地化字符串。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本块 的本地化字符串。
        /// </summary>
        internal static string TextBlock {
            get {
                return ResourceManager.GetString("TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框 的本地化字符串。
        /// </summary>
        internal static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本对话框 的本地化字符串。
        /// </summary>
        internal static string TextDialog {
            get {
                return ResourceManager.GetString("TextDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本对话框（控件中） 的本地化字符串。
        /// </summary>
        internal static string TextDialogInControl {
            get {
                return ResourceManager.GetString("TextDialogInControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本对话框，带计时器 的本地化字符串。
        /// </summary>
        internal static string TextDialogWithTimer {
            get {
                return ResourceManager.GetString("TextDialogWithTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间条 的本地化字符串。
        /// </summary>
        internal static string TimeBar {
            get {
                return ResourceManager.GetString("TimeBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间选择器 的本地化字符串。
        /// </summary>
        internal static string TimePicker {
            get {
                return ResourceManager.GetString("TimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是标题 的本地化字符串。
        /// </summary>
        internal static string TitleDemoStr1 {
            get {
                return ResourceManager.GetString("TitleDemoStr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此项必填 的本地化字符串。
        /// </summary>
        internal static string TitleDemoStr2 {
            get {
                return ResourceManager.GetString("TitleDemoStr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题在左侧 的本地化字符串。
        /// </summary>
        internal static string TitleDemoStr3 {
            get {
                return ResourceManager.GetString("TitleDemoStr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换按钮 的本地化字符串。
        /// </summary>
        internal static string ToggleButton {
            get {
                return ResourceManager.GetString("ToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具条 的本地化字符串。
        /// </summary>
        internal static string ToolBar {
            get {
                return ResourceManager.GetString("ToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 穿梭框 的本地化字符串。
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容过渡控件 的本地化字符串。
        /// </summary>
        internal static string TransitioningContentControl {
            get {
                return ResourceManager.GetString("TransitioningContentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 树视图 的本地化字符串。
        /// </summary>
        internal static string TreeView {
            get {
                return ResourceManager.GetString("TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试试关闭程序吧？ 的本地化字符串。
        /// </summary>
        internal static string Try2CloseApp {
            get {
                return ResourceManager.GetString("Try2CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等间距布局 的本地化字符串。
        /// </summary>
        internal static string UniformSpacingPanel {
            get {
                return ResourceManager.GetString("UniformSpacingPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件 的本地化字符串。
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传;上传中 的本地化字符串。
        /// </summary>
        internal static string UploadStr {
            get {
                return ResourceManager.GetString("UploadStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可见性 的本地化字符串。
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VS 插件 的本地化字符串。
        /// </summary>
        internal static string Vsix {
            get {
                return ResourceManager.GetString("Vsix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瀑布流 的本地化字符串。
        /// </summary>
        internal static string WaterfallPanel {
            get {
                return ResourceManager.GetString("WaterfallPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印 的本地化字符串。
        /// </summary>
        internal static string Watermark {
            get {
                return ResourceManager.GetString("Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站 的本地化字符串。
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口 的本地化字符串。
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
