<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>XStudio</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <NoWarn>$(NoWarn);CS1591;CS0436;CS8618</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <NoWarn>$(NoWarn);CS1591;CS0436;CS8618</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="EntityFrameworkCore\CustomDbContextProvider.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Include="EntityFrameworkCore\CustomDbContextProvider.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0" />
		<ProjectReference Include="..\XStudio.Domain\XStudio.Domain.csproj" />
		<PackageReference Include="DM.Microsoft.EntityFrameworkCore" Version="8.0.0.28188" />
		<PackageReference Include="ShardingCore" Version="7.8.1.22" />
		<PackageReference Include="Volo.Abp.EntityFrameworkCore.MySQL" Version="9.0.0" />
		<PackageReference Include="Volo.Abp.PermissionManagement.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Volo.Abp.SettingManagement.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Volo.Abp.Identity.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Volo.Abp.BackgroundJobs.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Volo.Abp.AuditLogging.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Volo.Abp.TenantManagement.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Volo.Abp.FeatureManagement.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Volo.Abp.OpenIddict.EntityFrameworkCore" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
